### ISSUE TITLE
Requested resource not found

### ISSUE THREAD

**Issue by akchro** [Jerusus/discordwebdiplomacy#6]
I tried hosting the bot myself but when I try to run it on Heroku I get it crashes and I get this error.
```
2022-05-07T18:23:02.434458+00:00 app[worker.1]: Running private scan...
2022-05-07T18:23:02.735520+00:00 app[worker.1]: Unable to read item. Error JSON: {
2022-05-07T18:23:02.735534+00:00 app[worker.1]: "message": "Requested resource not found",
2022-05-07T18:23:02.735534+00:00 app[worker.1]: "code": "ResourceNotFoundException",
2022-05-07T18:23:02.735535+00:00 app[worker.1]: "time": "2022-05-07T18:23:02.735Z",
2022-05-07T18:23:02.735535+00:00 app[worker.1]: "requestId": "GNUD308QNCGQCLDPI6H842JNPBVV4KQNSO5AEMVJF66Q9ASUAAJG",
2022-05-07T18:23:02.735536+00:00 app[worker.1]: "statusCode": 400,
2022-05-07T18:23:02.735537+00:00 app[worker.1]: "retryable": false,
2022-05-07T18:23:02.735537+00:00 app[worker.1]: "retryDelay": 47.92217966013014
2022-05-07T18:23:02.735538+00:00 app[worker.1]: }
```

**Comment by Jerusus** [comment]
Did you set up your own DynamoDB on AWS? Did you follow all the steps in https://github.com/Jerusus/discordwebdiplomacy#self-hosting ?

**Comment by akchro** [comment]
> Did you set up your own DynamoDB on AWS? Did you follow all the steps in https://github.com/Jerusus/discordwebdiplomacy#self-hosting ?


Yeah, I set up DynamoDB and made the tables. Heres a picture:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/75696154/167324577-687fae2a-ef96-4baa-b608-22226dbaacbd.png">

**Comment by Jerusus** [comment]
Do you have config vars in Heroku set with the correct values?
Under https://dashboard.heroku.com/apps/YOUR_APP_HERE/settings

![image](https://user-images.githubusercontent.com/10250263/167333479-a6b782e6-2e10-46ce-b677-dc3145a426cd.png)

**Comment by Jerusus** [comment]
The error message you are getting means the bot is failing whenever it is trying to read from the PlayerSubscription table. It is possible that your table was created in a different AWS region. The bot is hardcoded to us-west-2 right now. You might need to change it.

https://github.com/Jerusus/discordwebdiplomacy/blob/39aff4c9e5f727c15ae4d4078ce8b277b04c432e/src/app.js#L26

**Comment by akchro** [comment]
It seems my AWS region was us-west-1 so I changed the region to that and I got it to work. Thank you!

**Comment by akchro** [comment]
Actually nevermind
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/75696154/167350887-95dae15c-a715-4192-b8d5-caaede53ea7c.png">

**Comment by Jerusus** [comment]
Sorry I can't really tell what's going wrong from just this image. Did you get it to work at first and then it broke? I just noticed that 'us-west-2' is hardcoded in several files, you might need to find all instances of that to update it, or change your AWS region to us-west-2

Unrelated to your current error, one more thing you might need to do is change your Heroku dyno from 'worker' to 'web'. Scale down your worker and scale up web https://devcenter.heroku.com/articles/procfile#scaling-a-process-type
This allows for a heartbeat ping that runs so the bot doesn't go to sleep.

**Comment by akchro** [comment]
I've changed all the hardcoded values to us-west-1 and I don't get those errors anymore but now I get a different error. Also, I thought Web was the dyno that went to sleep, I will check that out.

Here are the logs:
```
2022-05-09T17:05:27.000000+00:00 app[api]: Build succeeded
2022-05-09T17:05:28.213817+00:00 heroku[worker.1]: Starting process with command `npm start`
2022-05-09T17:05:28.926218+00:00 heroku[worker.1]: State changed from starting to up
2022-05-09T17:05:30.441552+00:00 app[worker.1]: 
2022-05-09T17:05:30.441571+00:00 app[worker.1]: > discordwebdiplomacy@1.0.0 start
2022-05-09T17:05:30.441572+00:00 app[worker.1]: > node src/app.js
2022-05-09T17:05:30.441573+00:00 app[worker.1]: 
2022-05-09T17:05:31.024539+00:00 app[worker.1]: Listening on 48822
2022-05-09T17:05:31.386257+00:00 app[worker.1]: Logged in!
2022-05-09T17:05:31.386345+00:00 app[worker.1]: Running private scan...
2022-05-09T17:05:31.395282+00:00 app[worker.1]: Running public scan...
2022-05-09T17:05:31.400556+00:00 app[worker.1]: DiscordWebDiplomacy started. 3 guilds, 38 channels, and 1 users.
2022-05-09T17:07:31.051400+00:00 app[worker.1]: Running private scan...
2022-05-09T17:09:31.065730+00:00 app[worker.1]: Running private scan...
2022-05-09T17:10:31.026712+00:00 app[worker.1]: /app/node_modules/node-fetch/lib/index.js:1305
2022-05-09T17:10:31.026720+00:00 app[worker.1]: throw new TypeError('Only absolute URLs are supported');
2022-05-09T17:10:31.026721+00:00 app[worker.1]: ^
2022-05-09T17:10:31.026721+00:00 app[worker.1]: 
2022-05-09T17:10:31.026721+00:00 app[worker.1]: TypeError: Only absolute URLs are supported
2022-05-09T17:10:31.026723+00:00 app[worker.1]: at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
2022-05-09T17:10:31.026724+00:00 app[worker.1]: at /app/node_modules/node-fetch/lib/index.js:1410:19
2022-05-09T17:10:31.026724+00:00 app[worker.1]: at new Promise (<anonymous>)
2022-05-09T17:10:31.026724+00:00 app[worker.1]: at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
2022-05-09T17:10:31.026725+00:00 app[worker.1]: at Timeout._onTimeout (/app/src/app.js:71:3)
2022-05-09T17:10:31.026725+00:00 app[worker.1]: at listOnTimeout (node:internal/timers:559:17)
2022-05-09T17:10:31.026725+00:00 app[worker.1]: at processTimers (node:internal/timers:502:7)
2022-05-09T17:10:31.254555+00:00 heroku[worker.1]: Process exited with status 1
2022-05-09T17:10:31.576683+00:00 heroku[worker.1]: State changed from up to crashed
2022-05-09T17:10:31.580123+00:00 heroku[worker.1]: State changed from crashed to starting
```

**Comment by Jerusus** [comment]
Yeah changing to web dyno should fix this. My explanation might be incorrect, but when I was developing this I found I needed to use a web dyno to get some feature to work.

Either switch to a web dyno, or modify Timeout._onTimeout (/app/src/app.js:71:3) to remove the self ping.

**Comment by akchro** [comment]
I tried to change it to web and got these logs:
```
2022-05-09T17:40:13.183349+00:00 app[web.1]: Running private scan...
2022-05-09T17:42:13.194026+00:00 app[web.1]: Running private scan...
2022-05-09T17:43:13.152734+00:00 app[web.1]: /app/node_modules/node-fetch/lib/index.js:1305
2022-05-09T17:43:13.152752+00:00 app[web.1]: throw new TypeError('Only absolute URLs are supported');
2022-05-09T17:43:13.152753+00:00 app[web.1]: ^
2022-05-09T17:43:13.152753+00:00 app[web.1]: 
2022-05-09T17:43:13.152753+00:00 app[web.1]: TypeError: Only absolute URLs are supported
2022-05-09T17:43:13.152754+00:00 app[web.1]: at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
2022-05-09T17:43:13.152754+00:00 app[web.1]: at /app/node_modules/node-fetch/lib/index.js:1410:19
2022-05-09T17:43:13.152754+00:00 app[web.1]: at new Promise (<anonymous>)
2022-05-09T17:43:13.152755+00:00 app[web.1]: at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
2022-05-09T17:43:13.152755+00:00 app[web.1]: at Timeout._onTimeout (/app/src/app.js:71:3)
2022-05-09T17:43:13.152755+00:00 app[web.1]: at listOnTimeout (node:internal/timers:559:17)
2022-05-09T17:43:13.152755+00:00 app[web.1]: at processTimers (node:internal/timers:502:7)
2022-05-09T17:43:13.299790+00:00 heroku[web.1]: Process exited with status 1
2022-05-09T17:43:13.489681+00:00 heroku[web.1]: State changed from up to crashed
2022-05-09T17:43:13.504540+00:00 heroku[web.1]: State changed from crashed to starting
2022-05-09T17:43:16.258603+00:00 heroku[web.1]: Starting process with command `npm start`
2022-05-09T17:43:18.074041+00:00 app[web.1]: 
2022-05-09T17:43:18.074058+00:00 app[web.1]: > discordwebdiplomacy@1.0.0 start
2022-05-09T17:43:18.074058+00:00 app[web.1]: > node src/app.js
2022-05-09T17:43:18.074059+00:00 app[web.1]: 
2022-05-09T17:43:18.612141+00:00 app[web.1]: Listening on 28036
2022-05-09T17:43:18.938130+00:00 app[web.1]: Logged in!
2022-05-09T17:43:18.938224+00:00 app[web.1]: Running private scan...
2022-05-09T17:43:18.946765+00:00 app[web.1]: Running public scan...
2022-05-09T17:43:18.951876+00:00 app[web.1]: DiscordWebDiplomacy started. 3 guilds, 38 channels, and 1 users.
2022-05-09T17:43:19.081780+00:00 heroku[web.1]: State changed from starting to up
2022-05-09T17:45:18.610637+00:00 app[web.1]: Running private scan...
2022-05-09T17:47:18.618482+00:00 app[web.1]: Running private scan...
2022-05-09T17:48:18.616434+00:00 app[web.1]: /app/node_modules/node-fetch/lib/index.js:1305
2022-05-09T17:48:18.616444+00:00 app[web.1]: throw new TypeError('Only absolute URLs are supported');
2022-05-09T17:48:18.616445+00:00 app[web.1]: ^
2022-05-09T17:48:18.616445+00:00 app[web.1]: 
2022-05-09T17:48:18.616445+00:00 app[web.1]: TypeError: Only absolute URLs are supported
2022-05-09T17:48:18.616446+00:00 app[web.1]: at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
2022-05-09T17:48:18.616446+00:00 app[web.1]: at /app/node_modules/node-fetch/lib/index.js:1410:19
2022-05-09T17:48:18.616447+00:00 app[web.1]: at new Promise (<anonymous>)
2022-05-09T17:48:18.616447+00:00 app[web.1]: at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
2022-05-09T17:48:18.616447+00:00 app[web.1]: at Timeout._onTimeout (/app/src/app.js:71:3)
2022-05-09T17:48:18.616448+00:00 app[web.1]: at listOnTimeout (node:internal/timers:559:17)
2022-05-09T17:48:18.616448+00:00 app[web.1]: at processTimers (node:internal/timers:502:7)
2022-05-09T17:48:18.743354+00:00 heroku[web.1]: Process exited with status 1
2022-05-09T17:48:18.984134+00:00 heroku[web.1]: State changed from up to crashed
2022-05-09T18:45:00.004453+00:00 heroku[web.1]: State changed from crashed to starting
2022-05-09T18:45:02.928656+00:00 heroku[web.1]: Starting process with command `npm start`
2022-05-09T18:45:05.040318+00:00 app[web.1]: 
2022-05-09T18:45:05.040331+00:00 app[web.1]: > discordwebdiplomacy@1.0.0 start
2022-05-09T18:45:05.040331+00:00 app[web.1]: > node src/app.js
2022-05-09T18:45:05.040332+00:00 app[web.1]: 
2022-05-09T18:45:05.584212+00:00 app[web.1]: Listening on 27562
2022-05-09T18:45:05.842260+00:00 app[web.1]: Logged in!
2022-05-09T18:45:05.842391+00:00 app[web.1]: Running private scan...
2022-05-09T18:45:05.855845+00:00 app[web.1]: Running public scan...
2022-05-09T18:45:05.859924+00:00 app[web.1]: DiscordWebDiplomacy started. 3 guilds, 38 channels, and 1 users.
2022-05-09T18:45:05.931011+00:00 heroku[web.1]: State changed from starting to up
2022-05-09T18:47:05.605358+00:00 app[web.1]: Running private scan...
2022-05-09T18:49:05.617627+00:00 app[web.1]: Running private scan...
2022-05-09T18:50:05.585856+00:00 app[web.1]: /app/node_modules/node-fetch/lib/index.js:1305
2022-05-09T18:50:05.585863+00:00 app[web.1]: throw new TypeError('Only absolute URLs are supported');
2022-05-09T18:50:05.585865+00:00 app[web.1]: ^
2022-05-09T18:50:05.585865+00:00 app[web.1]: 
2022-05-09T18:50:05.585865+00:00 app[web.1]: TypeError: Only absolute URLs are supported
2022-05-09T18:50:05.585866+00:00 app[web.1]: at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
2022-05-09T18:50:05.585866+00:00 app[web.1]: at /app/node_modules/node-fetch/lib/index.js:1410:19
2022-05-09T18:50:05.585867+00:00 app[web.1]: at new Promise (<anonymous>)
2022-05-09T18:50:05.585867+00:00 app[web.1]: at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
2022-05-09T18:50:05.585867+00:00 app[web.1]: at Timeout._onTimeout (/app/src/app.js:71:3)
2022-05-09T18:50:05.585868+00:00 app[web.1]: at listOnTimeout (node:internal/timers:559:17)
2022-05-09T18:50:05.585868+00:00 app[web.1]: at processTimers (node:internal/timers:502:7)
2022-05-09T18:50:05.752595+00:00 heroku[web.1]: Process exited with status 1
2022-05-09T18:50:06.017783+00:00 heroku[web.1]: State changed from up to crashed
2022-05-09T19:06:23.577514+00:00 heroku[web.1]: State changed from crashed to starting
2022-05-09T19:06:26.599496+00:00 heroku[web.1]: Starting process with command `npm start`
2022-05-09T19:06:29.536947+00:00 app[web.1]: 
2022-05-09T19:06:29.536963+00:00 app[web.1]: > discordwebdiplomacy@1.0.0 start
2022-05-09T19:06:29.536963+00:00 app[web.1]: > node src/app.js
2022-05-09T19:06:29.536964+00:00 app[web.1]: 
2022-05-09T19:06:30.321882+00:00 app[web.1]: Listening on 13761
2022-05-09T19:06:30.643829+00:00 app[web.1]: Logged in!
2022-05-09T19:06:30.644027+00:00 app[web.1]: Running private scan...
2022-05-09T19:06:30.660979+00:00 app[web.1]: Running public scan...
2022-05-09T19:06:30.668259+00:00 app[web.1]: DiscordWebDiplomacy started. 3 guilds, 38 channels, and 1 users.
2022-05-09T19:06:30.684044+00:00 heroku[web.1]: State changed from starting to up
2022-05-09T19:08:30.344131+00:00 app[web.1]: Running private scan...
2022-05-09T19:10:30.358890+00:00 app[web.1]: Running private scan...
2022-05-09T19:11:30.323443+00:00 app[web.1]: /app/node_modules/node-fetch/lib/index.js:1305
2022-05-09T19:11:30.323452+00:00 app[web.1]: throw new TypeError('Only absolute URLs are supported');
2022-05-09T19:11:30.323453+00:00 app[web.1]: ^
2022-05-09T19:11:30.323453+00:00 app[web.1]: 
2022-05-09T19:11:30.323453+00:00 app[web.1]: TypeError: Only absolute URLs are supported
2022-05-09T19:11:30.323454+00:00 app[web.1]: at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
2022-05-09T19:11:30.323454+00:00 app[web.1]: at /app/node_modules/node-fetch/lib/index.js:1410:19
2022-05-09T19:11:30.323455+00:00 app[web.1]: at new Promise (<anonymous>)
2022-05-09T19:11:30.323455+00:00 app[web.1]: at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
2022-05-09T19:11:30.323456+00:00 app[web.1]: at Timeout._onTimeout (/app/src/app.js:71:3)
2022-05-09T19:11:30.323456+00:00 app[web.1]: at listOnTimeout (node:internal/timers:559:17)
2022-05-09T19:11:30.323457+00:00 app[web.1]: at processTimers (node:internal/timers:502:7)
2022-05-09T19:11:30.566355+00:00 heroku[web.1]: Process exited with status 1
2022-05-09T19:11:30.633285+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by Jerusus** [comment]
On your heroku dashboard, go to settings -> config vars. You need to set a HOST value. Your value will be different than what I have here.

![image](https://user-images.githubusercontent.com/10250263/167516252-ca3b432f-83c3-442c-94c4-4643f95e6b69.png)

The value you should set it to be can be found on the same page under 'Domains'

![image](https://user-images.githubusercontent.com/10250263/167516326-bd16a8e5-c761-4829-8a8e-13f3031810dc.png)

**Comment by akchro** [comment]
Ah, now it works. Thank you!
